# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xASQL36dIRpA9n877UXLuENNg9S2GWTN

This script installs the required Python libraries for Implimenting VQE Algorithm (PySCF and Qiskit).
"""

!pip install qiskit==1.0.1 pyscf==2.6.1 qiskit_algorithms==0.3.0 qiskit_nature==0.7.2